print_designer/hooks.py, print_designer/install.py
Print Designer is not supported in version-14 so only allow installing if framework version is develop or more then v14.
=> fix: check framework version before install

print_designer/print_designer/client_scripts/print.js
load pdfjsLib from designer_pdf instead of on_page_load.
=> fix: load pdfjsLib if not available inside designer_pdf

print_designer/print_designer/client_scripts/print.js
If Network Printing is enabled on the Frappe Site, we should utilize the `printit` function from `frappe.ui.form.PrintView`.
=> Enable Network Printing

print_designer/public/js/print_designer/components/layout/AppBarcodeModal.vue, print_designer/public/js/print_designer/components/layout/AppDynamicTextModal.vue, print_designer/public/js/print_designer/store/MainStore.js, print_designer/public/js/print_designer/store/fetchMetaAndData.js
currently, print designer honours the `print_hide` property of fields, community feedback suggests that this should be configurable so added a toggle that will make even hidden fields visible.
https://github.com/frappe/print_designer/assets/39730881/50017253-f24a-403b-b57f-810d0585e5bb
Closes #65
=> feat: allow hidden fields

pyproject.toml
python-barcode version upgraded.
#89
=> chore: python-barcode version upgrade to 0.15.1

print_designer/print_designer/page/print_designer/print_designer.py
python-barcode library removed the dpi argument from calculate_size function, so we need to remove it from our code as well. https://github.com/WhyNotHugo/python-barcode/commit/f103c836b6bb12f16b39daca90b4f985b7d89bff
=> fix(minor): remove dpi arg from PDSVGWriter

print_designer/print_designer/page/print_designer/jinja/main.html, print_designer/public/js/print_designer/components/base/BaseDynamicText.vue, print_designer/public/js/print_designer/components/base/BaseStaticText.vue
When Text is preformatted, it is not wrapped and can go outside the page. added max-width to preformatted text to prevent this.
Also, removed white-space: nowrap; it was added because there was some issue with wkhtmltopdf which breaks text.
don't remember when this happens so will revert this if it breaks again.
Closes #22
=> fix: text outside page when preformatted

print_designer/patches/patch_utils.py
Print Designer's Schema is in JSON Fields
When we change/add/remove schema it is very difficult and time consuming to migrate. People who doesn't have context of entire data structure can't write patches.
I have added this so anyone can now modifiy elements by passing callback function and updating object that is passed to function without worrying about structure.
=> chore: added patch utils for easy migrations

print_designer/patches.txt, print_designer/patches/introduce_jinja.py, print_designer/print_designer/page/print_designer/jinja/main.html, print_designer/print_designer/page/print_designer/print_designer.py, print_designer/public/js/print_designer/PropertiesPanelState.js, print_designer/public/js/print_designer/components/base/BaseBarcode.vue, print_designer/public/js/print_designer/components/base/BaseDynamicTextSpanTag.vue, print_designer/public/js/print_designer/components/base/BaseStaticText.vue, print_designer/public/js/print_designer/components/layout/AppBarcodePreviewModal.vue, print_designer/public/js/print_designer/components/layout/AppDynamicPreviewModal.vue, print_designer/public/js/print_designer/defaultObjects.js
- Added Support for templates rendering when you need something custom.
- On Print Designer client side we use Simple JavaScript Templating ( microtemplate.js in framework ) to render the preview.
-  Modified main.html which is used to generate pdf to parse jinja where required.
- Added fallback value to barcode so it will return blank html if empty value is set.
https://github.com/frappe/print_designer/assets/39730881/c306590b-fab9-4761-828b-bd21e4f07c8d
Closes #74
=> feat: jinja rendering for print designer

print_designer/patches.txt, print_designer/patches/introduce_schema_versioning.py, print_designer/public/js/print_designer/store/ElementStore.js, print_designer/public/js/print_designer/store/MainStore.js
In some cases patching old data is not possible without user intervention. 
When This the case, we can change the schema version and handle in code until user opens print designer and it is handled on save.
=> feat(minor): add schema versioning

print_designer/public/js/print_designer/store/ElementStore.js
schema_version is suppose to indicate new data version. 
instead of updating it from db on load we will save it as old_schema_version 
As when we save, we are suppose to fix the state that we couldn't do using patches.
we want to fix the schema and update the schema version on save.
=> fix: don't update schema_version on load

print_designer/print_designer/page/print_designer/jinja/main.html, print_designer/public/js/print_designer/PropertiesPanelState.js, print_designer/public/js/print_designer/store/ElementStore.js, print_designer/public/js/print_designer/store/MainStore.js
As users can have multiple Tables. I have added a workaround to set any table as Primary and that table will span across multiple pages and everything after table will be printed after table.
Workaround Fixes : #103 
https://github.com/frappe/print_designer/assets/39730881/a57832d8-92b2-44c4-9878-09d7df3b994f
=> fix: allow setting primary table

print_designer/print_designer/page/print_designer/jinja/main.html
Now, thanks to #107 we can have table after primary table. so we need to use printX value if available.
which is basically location relative to primary table's bottom left corner.
There is chance this is create some weird wkhtmltopdf pdf issue.
=> fix: use printX for position of the table

print_designer/hooks.py, print_designer/pdf.py, print_designer/print_designer/page/print_designer/jinja/main.html, print_designer/print_designer/page/print_designer/print_designer.js, print_designer/print_designer/page/print_designer/print_designer.py, print_designer/public/js/print_designer/App.vue, print_designer/public/js/print_designer/components/base/BaseBarcode.vue, print_designer/public/js/print_designer/components/base/BaseDynamicTextSpanTag.vue, print_designer/public/js/print_designer/components/base/BaseStaticText.vue, print_designer/public/js/print_designer/components/layout/AppBarcodePreviewModal.vue, print_designer/public/js/print_designer/components/layout/AppCanvas.vue, print_designer/public/js/print_designer/components/layout/AppCodeEditor.vue, print_designer/public/js/print_designer/components/layout/AppPropertiesPanel.vue, print_designer/public/js/print_designer/components/layout/AppUserProvidedJinjaModal.vue, print_designer/public/js/print_designer/store/ElementStore.js, print_designer/public/js/print_designer/store/MainStore.js, print_designer/public/js/print_designer/store/fetchMetaAndData.js
feat: add custom data using jinja
Reason for adding this feature:
- to allow users to add custom data to the template using jinja
- It is not ideal to fetch data for every field in the template when it is shared at template level
- This feature allows users to add custom data at the template level using jinja
How to use this feature:
- Add custom template by clicking `Manage Custom Data` using print_designer
- on the last line make dictionary of data you want to send to template
- make sure to use `send_to_jinja` variable name.
like `{%- set send_to_jinja = {'key_to_access_in_template': 'value'} -%}`
Example:
Code shared below will make `status` and `custom_var` available in the template
```
{% set status = doc.status %}
{% set custom_var = "This is Custom Text Saved in Custom Variable" …
```
=> feat: custom jinja data template

print_designer/patches.txt, print_designer/patches/patch_utils.py, print_designer/patches/rerun_introduce_jinja.py
when rectangle is not in types list argument, it will not run on childrens.
however, it can have childrens that have one of specified types.
so run on patch_elements childrens when rectangle is not in types list.
also added introduce_jinja patch again as it wasn't applied on childrens
=> fix: patch utils to run on rectangle childrens

print_designer/public/js/print_designer/store/ElementStore.js
If there is empty table print format breaks and most likely it is user error so when user tries to save format with empty table we just show the error. and prevent saving.
closes #112
=> fix(misc): don't save format with missing table

print_designer/public/js/print_designer/components/layout/AppDynamicPreviewModal.vue, print_designer/public/js/print_designer/components/layout/AppHeader.vue, print_designer/public/js/print_designer/utils.js
previously, to rename print format you had to leave print designer go to the "Print Format" doctype and rename from there. Now i have added a option when you click on name of print format in print designer and you can rename it.
misc: moved selectElementContents to utils.js
fixes: #105 
https://github.com/frappe/print_designer/assets/39730881/270704c2-e8e4-47ad-a784-5e645f724d39
=> feat(minor): allow renaming print format from pd

print_designer/print_designer/page/print_designer/jinja/main.html
bootstrap in print style sets text color to black for all elements and as wkhtmltopdf doesn't allow setting color as unset :(
i added workaround to set the color to child text elements
=> fix: dynamic text color

print_designer/hooks.py, print_designer/print_designer/client_scripts/point_of_sale.js, print_designer/print_designer/client_scripts/print.js
added client script to update frappe.util.print function that is used in pos. Also, added option to trigger print on print view by passing it as URL Parameter. If trigger_print=1 is passed it will close the window in 5 second after print dialog is closed. This is added to maintain current behavior.
If this causes issue we can introduce 1 more arg for closing and pass when using frappe.util.print.
Before
https://github.com/frappe/print_designer/assets/39730881/158cb590-4334-470e-a36b-a88e56e10d0f
After
https://github.com/frappe/print_designer/assets/39730881/8d838875-f003-4150-9496-a0dc201b6d39
closes #164
=> fix: pos print and added trigger_print

print_designer/public/js/print_designer/components/base/BaseTable.vue
We check if Element is part of header / footer by checking starting postion and height. because of the border around the table container we had to leave atleast 1 px space between header and table. removed border so users can create more contected looking formats.
=> fix: remove border around table container

print_designer/print_designer/page/print_designer/jinja/main.html
in dynamic content new line / `<br>` was rendering even if value was empty. which leaves empty line in the content. this commit fixes that.
fixes: #206
=> fix: only render new line if value is present

print_designer/print_designer/page/print_designer/jinja/macros/spantag.html, print_designer/print_designer/page/print_designer/jinja/old_print_format.html
In dynamic content new line / `<br>` was rendering even if value was empty. which leaves empty line in the content. this commit fixes that for old_print_format jinja template.
also, added missing jinja code for suffix in new template.
=> fix: only render new line if value is present (develop)

package.json, print_designer/custom_fields.py, print_designer/default_formats.py, print_designer/hooks.py, print_designer/install.py, print_designer/patches.txt, print_designer/patches/create_custom_fields.py, print_designer/print_designer/client_scripts/print_format.js, print_designer/print_designer/overrides/print_format.py, print_designer/print_designer/page/print_designer/jinja/macros/image.html, print_designer/print_designer/page/print_designer/jinja/old_print_format.html, print_designer/public/js/print_designer/components/layout/AppCanvas.vue, print_designer/public/js/print_designer/store/ElementStore.js, yarn.lock
- Added Custom Field for Print Designer Template Location
- Added Hook to define folder location for Print Designer Templates ( location fallbacks to default_templates if not defined in hooks for export )
- when print designer is installed, loop over all apps and import standard templates.
- when any new app is installed, check if it has print designer templates and install them. - it also checks print_designer app for new templates and installs them.
- Modified export functionality for print formats that are made using print_designer. - it will export print format in custom directory if defined in hooks else in default_templates folder. 
- user / developer can define app where print format should be exported in print_designer_template_app field.
depends on : …
=> feat: default template import export

print_designer/print_designer/page/print_designer/jinja/macros/relative_containers.html, print_designer/print_designer/page/print_designer/jinja/macros/styles.html, print_designer/print_designer/page/print_designer/jinja/print_format.html, print_designer/public/js/print_designer/PropertiesPanelState.js, print_designer/public/js/print_designer/components/base/BaseTable.vue, print_designer/public/js/print_designer/components/layout/AppCanvas.vue, print_designer/public/js/print_designer/store/ElementStore.js
missing part of #205 
This will be merged if i can solve this issue. https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2367
Edit: Solved
=> feat!: columns in dynamic containers

print_designer/print_designer/page/print_designer/jinja/macros/spantag.html
recently, changed the logic to only render fields if the value is present. 
however, this caused an issue with page fields, as they are always empty and are updated by wkhtmltopdf.
fixes: #218
=> fix: render empty field for page field.

print_designer/public/js/print_designer/components/base/BaseStaticText.vue
This will break styled text, but i think plain text is more used. 
chrome adds unnecessary tags so only saving innerText instead of innerHTML for now.
fixes #129 #221
=> fix: static text only save inner text

print_designer/print_designer/page/print_designer/jinja/macros/render_google_fonts.html
we save font details saved in json object and then we generate url from it using jinja template. there was a edge case where `;` was not being added at the end of normal weight.
incorrect https://fonts.googleapis.com/css2?family=JetBrains%20Mono:ital,wght@0,400;0,5001,400 
correct https://fonts.googleapis.com/css2?family=JetBrains%20Mono:ital,wght@0,400;0,500;1,400
=> fix: google font url generator edge case

print_designer/patches/patch_utils.py
when patch was modified to also run on print_designer_print_formats field. i accidentally messed up lines and spacing, this commit fixes it. went unnoticed because the patch was already applied locally in the first run.
=> chore: fix typo in patch_utils

print_designer/pdf.py
Instead of rendering template directly call the framework pdf_body_html function to render the html. this prevents incorrect possible source of error as shown below.
=> fix(minor): call the framework pdf_body_html func

print_designer/print_designer/page/print_designer/jinja/macros/styles.html
fixed html that was broken on modern browsers due to changes made by recursive containers PR.
=> fix(minor): fix html for modern browsers recursive

print_designer/patches.txt, print_designer/patches/patch_utils.py
As patch utils are used by all patches there isn't print_designer_print_format field when old patches are running and there is no need to try and update it.
Also, moved custom_field_patch in pre_model_sync
=> fix: patch utils for old patches

print_designer/patches.txt, print_designer/patches/convert_formats_for_recursive_container.py, print_designer/patches/move_header_footers_to_new_schema.py
forgot to patch body elements to be inside page object which caused breakage in formats.
also updated layoutType property in row and column object.
chore: updated correct description for the patch
=> fix: patch old formats for multi page

print_designer/public/js/print_designer/utils.js
In refactor of update for dynamic data i accidentally mutated the field.value object in getFormattedValue. which in turn triggers getFormattedValue function. this commit fixes it by updating local variable instead of field.value object.
Not sure why this loop didn't crash in local development setup.
fixes #292
=> fix: accidental mutation of field.value

print_designer/print_designer/page/print_designer/jinja/macros/spantag.html, print_designer/public/js/print_designer/utils.js
signature field is saved as base64 encoded string in the database. i just added img tag and set the src attribute to the base64 encoded string.
https://github.com/frappe/print_designer/assets/39730881/96137271-bbb1-4556-890d-c981aa69b074
fixes #110 #276
=> feat: allow signature in dynamic text

print_designer/print_designer/page/print_designer/print_designer.py, print_designer/public/js/print_designer/components/layout/AppDynamicTextModal.vue, print_designer/public/js/print_designer/store/fetchMetaAndData.js
using with_doctype stores meta in localstorage which causes it to be full and is not required to replaced it with get_meta method in print designer
=> refactor(minor): call whitelisted method to get meta

print_designer/public/js/print_designer/store/ElementStore.js
from rectangle removed relative-column as there isn't any flex related css for column adding that class caused border to be removed when it was applied from rectangle class.
also, added filter to remove classes getting added multiple times.
=> fix: removed relative-column class from rectangle

print_designer/public/js/print_designer/composables/AttachKeyBindings.js
After Multi page refactor, key bindings logic was not working as expected. There was a check which would return if target was not document.body but that was incorrect as we changed Structure of canvas area.
=> fix: update key bindings logic as per new Structure

print_designer/public/js/print_designer/composables/AttachKeyBindings.js
not sure why but i believe focus element is different in some cases which is causing keybinding to not work so reverted changes from #344.
=> fix(minor): revert keybinding changes

print_designer/public/js/print_designer/components/layout/AppPages.vue
In production, mutation.events is undefined which causes error while deleting element.
=> fix(minor): fix error deleting element

print_designer/print_designer/client_scripts/print.js
i recently removed pdfjs from source code as it was used for better ux. however, as it was dependancy nighmare i removed it in favour of browser's  built in pdf viewer.
i also removed download_pdf button as pdf viewer has download icon (atleasr Chrome/Mozilla).
i recently found that some browser's default pdf viewer doesn't have download button so added one in menu.
=> fix: added menu option to download pdf
