- print_designer/print_designer/page/print_designer/print_designer.js
- print_designer/public/js/print_designer/store/fetchMetaAndData.js
find last viewed doc from route history and set currentDoc if exists.
closes #24
> fix: set currentDoc from route history

- print_designer/public/js/print_designer/components/layout/AppBarcodePreviewModal.vue
- print_designer/public/js/print_designer/components/layout/AppDynamicPreviewModal.vue
- print_designer/public/js/print_designer/components/layout/AppModal.vue
- print_designer/public/js/print_designer/composables/AttachKeyBindings.js
> fix: dynamic preview & keybindings cleanup

- print_designer/print_designer/page/print_designer/jinja/main.html
- print_designer/public/js/print_designer/components/base/BaseRectangle.vue
Added barcode inside rectangle and changed quiet zone in main.html to match print designer
> fix: add barcode inside rectangle

- print_designer/public/js/print_designer/components/layout/AppDynamicPreviewModal.vue
- print_designer/public/js/print_designer/components/layout/AppModal.vue
added check for contenteditable element as well
> fix (minor): check if activeElement is contentEditable as well

- print_designer/public/js/print_designer/PropertiesPanelState.js
- print_designer/public/js/print_designer/components/layout/AppPropertiesPanelSection.vue
- print_designer/public/js/print_designer/pageSizes.js
Custom Size were supported from the start but because there were some issue with properties panel it prevented the use of it.
> fix: support for custom page size

- print_designer/print_designer/page/print_designer/jinja/main.html
This is a quick fix and will need to revisit to properly implement Translations.
> fix(minor): wrap static and label inside translate function

- print_designer/print_designer/page/print_designer/print_designer.js
- print_designer/public/js/print_designer/store/ElementStore.js
- print_designer/public/js/print_designer/store/fetchMetaAndData.js
When Preview Document that is used in print designer no longer exists it goes into infinite loop. check if document exist before setting.
closes #55
> fix: handle when document doesn't exist

- print_designer/print_designer/page/print_designer/print_designer.js
update doctype variable to actual value.
> fix: get correct doctype from route_history

- print_designer/public/js/print_designer/components/layout/AppDynamicTextModal.vue
This just prevents error and allows user to select fields still need to add feedback in child table with placeholders
> fix(minor): handle no row is state in child table

- print_designer/print_designer/page/print_designer/jinja/main.html
- print_designer/public/js/print_designer/components/base/BaseDynamicText.vue
quill content have div, so had to change from p tag to div. 
( there is chance this will break some styles )
Closes #73 #62
> fix: change dynamic text to div for quill

- print_designer/public/js/print_designer/components/layout/AppHeader.vue
- for easier navigation added link to home page on logo
- exit button goes to previous page if exists, otherwise to home page
closes #84
> fix: add exit button and link to logo

- print_designer/public/js/print_designer/store/MainStore.js
Previously, the Name/Title fields were only allowed in main doctype 
as it is required in the linked fields as well i have added the option.
Closes #78
> feat: allow Name/Title fields from linked doctypes

- print_designer/print_designer/page/print_designer/print_designer.py
- print_designer/public/js/print_designer/components/base/BaseDynamicTextSpanTag.vue
- print_designer/public/js/print_designer/components/layout/AppCanvas.vue
Jinja & Custom Data Feature assumes there is always a doc available. which is not always the case so updated the code accordingly.
> fix: Jinja & Custom Data when no doc is available

- print_designer/print_designer/page/print_designer/jinja/main.html
- print_designer/print_designer/page/print_designer/print_designer.py
- print_designer/public/js/print_designer/components/base/BaseBarcode.vue
- print_designer/public/js/print_designer/components/base/BaseDynamicTextSpanTag.vue
- print_designer/public/js/print_designer/components/base/BaseStaticText.vue
- print_designer/public/js/print_designer/components/layout/AppBarcodePreviewModal.vue
- print_designer/public/js/print_designer/components/layout/AppCanvas.vue
- print_designer/public/js/print_designer/store/fetchMetaAndData.js
now when there is error in user provided jinja template, it will console.error the error silently.
> fix: handle missing doc and bugs caused by jinja.

- print_designer/print_designer/client_scripts/print.js
enable_print_server is string so "0" is true added parseInt to convert string to int.
> fix(minor): typo enable_print_server is string

- print_designer/print_designer/page/print_designer/jinja/main.html
i removed the white-space css in #94 as i was unable to reproduce the issue that it fixed well now i found it so added it again. also added 2 px to max-width as text was getting cut
closes #137
> fix: issues caused by white-space

- print_designer/patches.txt
- print_designer/patches/introduce_table_alt_row_styles.py
- print_designer/print_designer/page/print_designer/jinja/main.html
- print_designer/print_designer/page/print_designer/print_designer.js
- print_designer/public/js/print_designer/PropertiesPanelState.js
- print_designer/public/js/print_designer/components/base/BaseTable.vue
- print_designer/public/js/print_designer/components/base/BaseTableTd.vue
- print_designer/public/js/print_designer/components/layout/AppCanvas.vue
- print_designer/public/js/print_designer/defaultObjects.js
- print_designer/public/js/print_designer/frappeControl.js
- print_designer/public/js/print_designer/globalStyles.js
- print_designer/public/js/print_designer/store/ElementStore.js
- print_designer/public/js/print_designer/store/MainStore.js
- print_designer/public/js/print_designer/utils.js
Added Option to style Alternate lines of table.
https://github.com/frappe/print_designer/assets/39730881/b7e91951-32ac-4d03-b5c2-109b00238afc
> feat: alternate table row style

- print_designer/public/js/print_designer/PropertiesPanelState.js
- print_designer/public/js/print_designer/components/base/BaseTable.vue
- print_designer/public/js/print_designer/components/layout/AppCanvas.vue
- print_designer/public/js/print_designer/components/layout/AppPropertiesFrappeControl.vue
- print_designer/public/js/print_designer/store/fetchMetaAndData.js
pre-fill table when table is empty.
https://github.com/frappe/print_designer/assets/39730881/9bcb6338-e728-4b0b-9364-db79a25626b7
This closes #28
> fix: improve table element

- README.md
Improve documentation for ARM based installation.
Source:
- https://github.com/Automattic/node-canvas/issues/2306
> chore: add canvas steps for linux with ARM

- print_designer/pdf.py
- print_designer/print_designer/client_scripts/print.js
https://github.com/frappe/print_designer/assets/39730881/6464f4e0-f11c-49bf-b287-95295761c634
https://github.com/frappe/print_designer/assets/39730881/4c1539d0-7b85-43ea-9e3f-1afb76b7ca42
> fix: add error log on pdf generation

- print_designer/print_designer/client_scripts/point_of_sale.js
instead of copying the code, reference the original print util function https://github.com/frappe/print_designer/pull/185#discussion_r1512215722
> chore: reference original print function

- print_designer/patches.txt
- print_designer/patches/introduce_suffix_dynamic_content.py
- print_designer/print_designer/page/print_designer/jinja/main.html
- print_designer/public/js/print_designer/components/base/BaseDynamicTextSpanTag.vue
- print_designer/public/js/print_designer/components/layout/AppDynamicPreviewModal.vue
- print_designer/public/js/print_designer/components/layout/AppDynamicTextModal.vue
There are cases where user would like to add suffix such as ", " but that needs to be visible only if some field exist. Added option to add suffix in dynamic fields.
https://github.com/frappe/print_designer/assets/39730881/2538bfc3-c64d-4311-b699-dd548aea4fad
https://github.com/frappe/print_designer/assets/39730881/cc322488-4053-4357-a4ae-02c516044e76
> feat: option to add suffix in dynamic fields

- print_designer/public/js/print_designer/components/base/BaseTable.vue
Add missing style & applyStyleToHeader properties to the new columns
> fix: table new element column style

- print_designer/print_designer/page/print_designer/jinja/old_print_format.html
In #220 forgot to fix the issue  in old_print_format.html
> chore: fix render empty field for page field #220

- print_designer/patches.txt
- print_designer/patches/introduce_z_index.py
- print_designer/public/js/print_designer/PropertiesPanelState.js
- print_designer/public/js/print_designer/components/base/BaseBarcode.vue
- print_designer/public/js/print_designer/components/base/BaseDynamicText.vue
- print_designer/public/js/print_designer/components/base/BaseImage.vue
- print_designer/public/js/print_designer/components/base/BaseStaticText.vue
- print_designer/public/js/print_designer/components/base/BaseTable.vue
- print_designer/public/js/print_designer/frappeControl.js
- print_designer/public/js/print_designer/store/MainStore.js
now that i am sorting elements by starting x and y position. it messes up the overlapping designs that people are creating. this will allow people to set the zIndex of the element.
https://github.com/frappe/print_designer/assets/39730881/ac34ef50-e72c-45a7-a912-a01b94be027e
> feat: added zIndex style property.

- print_designer/print_designer/page/print_designer/jinja/macros/dynamictext.html
- print_designer/print_designer/page/print_designer/jinja/macros/rectangle.html
- print_designer/print_designer/page/print_designer/jinja/macros/render_element.html
- print_designer/print_designer/page/print_designer/jinja/macros/statictext.html
- print_designer/print_designer/page/print_designer/jinja/macros/table.html
In recent change we added 3 types of height fixed, auto, auto (min-height) so we converted property to string from boolean. check in dynamic text was for boolean so changed it to string comparison
> fix: change heightType check to string

- print_designer/public/js/print_designer/components/layout/AppDynamicTextModal.vue
- print_designer/public/js/print_designer/utils.js
- on copy/clone of barcode it was not making copy of dynamicData fields which caused changing of data in 1 barcode to replace data in other copied/cloned  barcode.
- do not update value in field incase it's jinja when AppDynamicTextModal is opened.
> fix: barcode clone and jinja dynamicData

- print_designer/public/js/print_designer/utils.js
only format image if it is inside row.
fixes #312 and https://discuss.frappe.io/t/dynamic-image-issue-in-print-designer/128237/
> fix: await formattedValue and don't format image url

- print_designer/install.py
This is not ideal but not also harmful as it will only install once. code checks if chrome is already installed and if not it will install it.
> chore: run chrome install after install

- print_designer/print_designer/client_scripts/print.js
As, there is quite difference in the print view in v15. pdf viewer was working fine with develop branch but not with v15. fixed the issue with proper css.
> fix(minor): print view in v15

- print_designer/hooks.py
- print_designer/install.py
Case of site update to new bench without it
Workaround till FC does it better
> fix(chromium-setup): Add cron to setup chromium when it's not available
